version: '2'
services:
  postgres:
    build: .
    image: postgres-postgis-src-local-1
    command: postgres -c listen_addresses='*'
    ports:
      - '5432:5432'
      - '2345:2345'
    cap_add:
      - ALL
    environment:
      POSTGRES_PASSWORD: 'password1'
      POSTGRES_DB: 'test'
    volumes:
      - postgres:/var/lib/postgres/data
volumes:
  postgres:
