version: '2'
services:
  postgres:
    build: .
    image: postgres-postgis-src-local-1
    ports:
      - '5432:5432'
      - '2345:2345'
    cap_add:
      - SYS_PTRACE
    environment:
      POSTGRES_PASSWORD: 'password1'
    volumes:
      - postgres:/var/lib/postgres/data
volumes:
  postgres:
